# Generated by Django 3.0.7 on 2021-04-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='corp_code',
            field=models.IntegerField(default=0),
        ),
    ]
