# Generated by Django 3.0.7 on 2021-04-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210429_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='corp_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
