# Generated by Django 3.0.7 on 2021-04-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('user_id', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('birth_date', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
