# Generated by Django 3.0.7 on 2021-04-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='portfolio',
            field=models.ManyToManyField(related_name='account_portfolio', through='portfolio.LikePortfolio', to='portfolio.Portfolio'),
        ),
    ]
