# Generated by Django 3.0.7 on 2021-04-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210421_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliostock',
            old_name='sheres_amount',
            new_name='shares_amount',
        ),
    ]
